### ISSUE TITLE
Push back loading

### ISSUE THREAD

**Issue by lunatic312** [lat9/ga4-analytics#25]
Loading needs to be moved after 140 otherwise this interferes with non-standard add to cart actions.

**Comment by lat9** [comment]
An example, please, so that I've got a means to validate.

**Comment by lunatic312** [comment]
Sorry, of course. I have a custom product type that uses an extra cart action.

If I add to cart, it runs the add to cart function but the item is not saved in the cart session. Moving GA4 to breakpoint 141 seems to resolve this as the extra cart actions are loaded at 140

**Comment by lat9** [comment]
Right, but if that load-point is moved then any 'base' cart-related actions will be missed since the cart-related actions, if present, are performed during the `main_cart_actions.php` script and subsequently redirected.

What processing is performed by your custom product type's extra-cart-action that the GA4 Analytics script is 'interfering with"?

**Comment by lunatic312** [comment]
It runs a function from "extra cart actions" on a class that is an extension of shopping cart add_cart

It seems that the shopping cart class runs, item is added, but subsequently removed after GA4 is triggered

**Comment by lat9** [comment]
Send me a PM on the Zen Cart forums (https://www.zen-cart.com/member.php?81053-lat9) with your direct email address so that I can get some additional information.  What you've supplied thus far is too vague to diagnose.

**Comment by lat9** [comment]
Closing due to lack of response.
